package com.zjrb.sjzsw.greendao;

import com.zjrb.sjzsw.entity.NewsChannel;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 *
 * 管理指定模式下的所有 DAO 对象，
 * DaoSession提供了一些通用的持久性方法比如插入、负载、更新、更新和删除实体。
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelDaoConfig;

    private final NewsChannelDao newsChannelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        newsChannelDaoConfig = daoConfigMap.get(NewsChannelDao.class).clone();
        newsChannelDaoConfig.initIdentityScope(type);

        newsChannelDao = new NewsChannelDao(newsChannelDaoConfig, this);

        registerDao(NewsChannel.class, newsChannelDao);
    }
    
    public void clear() {
        newsChannelDaoConfig.clearIdentityScope();
    }

    public NewsChannelDao getNewsChannelDao() {
        return newsChannelDao;
    }

}
