package com.zjrb.sjzsw.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zjrb.sjzsw.entity.GreenDaoTest;
import com.zjrb.sjzsw.entity.GreenDaoTest2;
import com.zjrb.sjzsw.entity.greenDaoUpdateTest;
import com.zjrb.sjzsw.entity.NewsChannel;

import com.zjrb.sjzsw.greendao.GreenDaoTestDao;
import com.zjrb.sjzsw.greendao.GreenDaoTest2Dao;
import com.zjrb.sjzsw.greendao.greenDaoUpdateTestDao;
import com.zjrb.sjzsw.greendao.NewsChannelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoTestDaoConfig;
    private final DaoConfig greenDaoTest2DaoConfig;
    private final DaoConfig greenDaoUpdateTestDaoConfig;
    private final DaoConfig newsChannelDaoConfig;

    private final GreenDaoTestDao greenDaoTestDao;
    private final GreenDaoTest2Dao greenDaoTest2Dao;
    private final greenDaoUpdateTestDao greenDaoUpdateTestDao;
    private final NewsChannelDao newsChannelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoTestDaoConfig = daoConfigMap.get(GreenDaoTestDao.class).clone();
        greenDaoTestDaoConfig.initIdentityScope(type);

        greenDaoTest2DaoConfig = daoConfigMap.get(GreenDaoTest2Dao.class).clone();
        greenDaoTest2DaoConfig.initIdentityScope(type);

        greenDaoUpdateTestDaoConfig = daoConfigMap.get(greenDaoUpdateTestDao.class).clone();
        greenDaoUpdateTestDaoConfig.initIdentityScope(type);

        newsChannelDaoConfig = daoConfigMap.get(NewsChannelDao.class).clone();
        newsChannelDaoConfig.initIdentityScope(type);

        greenDaoTestDao = new GreenDaoTestDao(greenDaoTestDaoConfig, this);
        greenDaoTest2Dao = new GreenDaoTest2Dao(greenDaoTest2DaoConfig, this);
        greenDaoUpdateTestDao = new greenDaoUpdateTestDao(greenDaoUpdateTestDaoConfig, this);
        newsChannelDao = new NewsChannelDao(newsChannelDaoConfig, this);

        registerDao(GreenDaoTest.class, greenDaoTestDao);
        registerDao(GreenDaoTest2.class, greenDaoTest2Dao);
        registerDao(greenDaoUpdateTest.class, greenDaoUpdateTestDao);
        registerDao(NewsChannel.class, newsChannelDao);
    }
    
    public void clear() {
        greenDaoTestDaoConfig.clearIdentityScope();
        greenDaoTest2DaoConfig.clearIdentityScope();
        greenDaoUpdateTestDaoConfig.clearIdentityScope();
        newsChannelDaoConfig.clearIdentityScope();
    }

    public GreenDaoTestDao getGreenDaoTestDao() {
        return greenDaoTestDao;
    }

    public GreenDaoTest2Dao getGreenDaoTest2Dao() {
        return greenDaoTest2Dao;
    }

    public greenDaoUpdateTestDao getGreenDaoUpdateTestDao() {
        return greenDaoUpdateTestDao;
    }

    public NewsChannelDao getNewsChannelDao() {
        return newsChannelDao;
    }

}
