package com.zjrb.sjzsw.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.zjrb.sjzsw.entity.NewsChannel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NEWS_CHANNEL".
*/
public class NewsChannelDao extends AbstractDao<NewsChannel, String> {

    public static final String TABLENAME = "NEWS_CHANNEL";

    /**
     * Properties of entity NewsChannel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property NewsChannelName = new Property(0, String.class, "newsChannelName", true, "NEWS_CHANNEL_NAME");
        public final static Property NewsChannelId = new Property(1, String.class, "newsChannelId", false, "NEWS_CHANNEL_ID");
        public final static Property NewsChannelType = new Property(2, String.class, "newsChannelType", false, "NEWS_CHANNEL_TYPE");
        public final static Property NewsChannelSelect = new Property(3, boolean.class, "newsChannelSelect", false, "NEWS_CHANNEL_SELECT");
        public final static Property NewsChannelIndex = new Property(4, int.class, "newsChannelIndex", false, "NEWS_CHANNEL_INDEX");
    }


    public NewsChannelDao(DaoConfig config) {
        super(config);
    }
    
    public NewsChannelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_CHANNEL\" (" + //
                "\"NEWS_CHANNEL_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: newsChannelName
                "\"NEWS_CHANNEL_ID\" TEXT," + // 1: newsChannelId
                "\"NEWS_CHANNEL_TYPE\" TEXT," + // 2: newsChannelType
                "\"NEWS_CHANNEL_SELECT\" INTEGER NOT NULL ," + // 3: newsChannelSelect
                "\"NEWS_CHANNEL_INDEX\" INTEGER NOT NULL );"); // 4: newsChannelIndex
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_CHANNEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, NewsChannel entity) {
        stmt.clearBindings();
 
        String newsChannelName = entity.getNewsChannelName();
        if (newsChannelName != null) {
            stmt.bindString(1, newsChannelName);
        }
 
        String newsChannelId = entity.getNewsChannelId();
        if (newsChannelId != null) {
            stmt.bindString(2, newsChannelId);
        }
 
        String newsChannelType = entity.getNewsChannelType();
        if (newsChannelType != null) {
            stmt.bindString(3, newsChannelType);
        }
        stmt.bindLong(4, entity.getNewsChannelSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getNewsChannelIndex());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, NewsChannel entity) {
        stmt.clearBindings();
 
        String newsChannelName = entity.getNewsChannelName();
        if (newsChannelName != null) {
            stmt.bindString(1, newsChannelName);
        }
 
        String newsChannelId = entity.getNewsChannelId();
        if (newsChannelId != null) {
            stmt.bindString(2, newsChannelId);
        }
 
        String newsChannelType = entity.getNewsChannelType();
        if (newsChannelType != null) {
            stmt.bindString(3, newsChannelType);
        }
        stmt.bindLong(4, entity.getNewsChannelSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getNewsChannelIndex());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public NewsChannel readEntity(Cursor cursor, int offset) {
        NewsChannel entity = new NewsChannel( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // newsChannelName
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // newsChannelId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // newsChannelType
            cursor.getShort(offset + 3) != 0, // newsChannelSelect
            cursor.getInt(offset + 4) // newsChannelIndex
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, NewsChannel entity, int offset) {
        entity.setNewsChannelName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setNewsChannelId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNewsChannelType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNewsChannelSelect(cursor.getShort(offset + 3) != 0);
        entity.setNewsChannelIndex(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(NewsChannel entity, long rowId) {
        return entity.getNewsChannelName();
    }
    
    @Override
    public String getKey(NewsChannel entity) {
        if(entity != null) {
            return entity.getNewsChannelName();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(NewsChannel entity) {
        return entity.getNewsChannelName() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
